# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddInventoryObj.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(523, 375)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -71, 339, 695))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.productNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.productNameLabel.setObjectName("productNameLabel")
        self.verticalLayout_2.addWidget(self.productNameLabel)
        self.productNameText = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.productNameText.setObjectName("productNameText")
        self.verticalLayout_2.addWidget(self.productNameText)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.itemIDLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.itemIDLabel.setObjectName("itemIDLabel")
        self.verticalLayout_2.addWidget(self.itemIDLabel)
        self.itemIDText = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.itemIDText.setObjectName("itemIDText")
        self.verticalLayout_2.addWidget(self.itemIDText)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.catCheckBox3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.catCheckBox3.setObjectName("catCheckBox3")
        self.gridLayout.addWidget(self.catCheckBox3, 3, 2, 1, 1)
        self.originCheckBox2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.originCheckBox2.setObjectName("originCheckBox2")
        self.gridLayout.addWidget(self.originCheckBox2, 1, 1, 1, 1)
        self.catCheckBox2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.catCheckBox2.setObjectName("catCheckBox2")
        self.gridLayout.addWidget(self.catCheckBox2, 3, 1, 1, 1)
        self.originLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.originLabel.setObjectName("originLabel")
        self.gridLayout.addWidget(self.originLabel, 0, 0, 1, 1)
        self.catCheckBox4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.catCheckBox4.setObjectName("catCheckBox4")
        self.gridLayout.addWidget(self.catCheckBox4, 3, 3, 1, 1)
        self.categoryLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.categoryLabel.setObjectName("categoryLabel")
        self.gridLayout.addWidget(self.categoryLabel, 2, 0, 1, 1)
        self.catCheckBox1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.catCheckBox1.setObjectName("catCheckBox1")
        self.gridLayout.addWidget(self.catCheckBox1, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.originCheckBox1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.originCheckBox1.setObjectName("originCheckBox1")
        self.gridLayout.addWidget(self.originCheckBox1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 3, 1, 1)
        self.originCheckBox3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.originCheckBox3.setObjectName("originCheckBox3")
        self.gridLayout.addWidget(self.originCheckBox3, 1, 2, 1, 1)
        self.originCheckBox4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.originCheckBox4.setObjectName("originCheckBox4")
        self.gridLayout.addWidget(self.originCheckBox4, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.priceLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout_2.addWidget(self.priceLabel)
        self.priceText = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.priceText.setObjectName("priceText")
        self.verticalLayout_2.addWidget(self.priceText)
        self.weightLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.weightLabel.setObjectName("weightLabel")
        self.verticalLayout_2.addWidget(self.weightLabel)
        self.weightText = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.weightText.setObjectName("weightText")
        self.verticalLayout_2.addWidget(self.weightText)
        self.descriptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout_2.addWidget(self.descriptionLabel)
        self.descriptionText = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.descriptionText.setObjectName("descriptionText")
        self.verticalLayout_2.addWidget(self.descriptionText)
        self.availableQuantityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.availableQuantityLabel.setObjectName("availableQuantityLabel")
        self.verticalLayout_2.addWidget(self.availableQuantityLabel)
        self.availableQuantitySpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.availableQuantitySpinBox.setObjectName("availableQuantitySpinBox")
        self.verticalLayout_2.addWidget(self.availableQuantitySpinBox)
        self.limitLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.limitLabel.setObjectName("limitLabel")
        self.verticalLayout_2.addWidget(self.limitLabel)
        self.limitSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.limitSpinBox.setObjectName("limitSpinBox")
        self.verticalLayout_2.addWidget(self.limitSpinBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.confirmButton = QtWidgets.QPushButton(Dialog)
        self.confirmButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_2.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/my_resources/Logos/Retriever Essential.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageUpload = QtWidgets.QLabel(Dialog)
        self.imageUpload.setMinimumSize(QtCore.QSize(150, 150))
        self.imageUpload.setMaximumSize(QtCore.QSize(16777215, 150))
        self.imageUpload.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.imageUpload.setFrameShape(QtWidgets.QFrame.Panel)
        self.imageUpload.setTextFormat(QtCore.Qt.PlainText)
        self.imageUpload.setAlignment(QtCore.Qt.AlignCenter)
        self.imageUpload.setPixmap(QtGui.QPixmap(":/my_resources/Logos/Upload Image.png"))
        self.imageUpload.setObjectName("imageUpload")
        self.verticalLayout.addWidget(self.imageUpload)
        
        # Add drag and drop feature for the imageUpload section
        self.imageUpload.setAcceptDrops(True) #enable drop function for the label
        self.imageUpload.dragEnterEvent = self.dragEnterEvent
        self.imageUpload.dropEvent = self.dropEvent
        self.imageUpload.mousePressEvent = self.selectImage
        
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem9)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.productNameLabel.setText(_translate("Dialog", "Product Name"))
        self.itemIDLabel.setText(_translate("Dialog", "Item ID"))
        self.catCheckBox3.setText(_translate("Dialog", "Cat 3"))
        self.originCheckBox2.setText(_translate("Dialog", "MD Food Bank"))
        self.catCheckBox2.setText(_translate("Dialog", "Cat2"))
        self.originLabel.setText(_translate("Dialog", "Origin:"))
        self.catCheckBox4.setText(_translate("Dialog", "Cat4"))
        self.categoryLabel.setText(_translate("Dialog", "Category:"))
        self.catCheckBox1.setText(_translate("Dialog", "Cat 1"))
        self.originCheckBox1.setText(_translate("Dialog", "Patel Brothers"))
        self.originCheckBox3.setText(_translate("Dialog", "Origin1"))
        self.originCheckBox4.setText(_translate("Dialog", "Origin 2"))
        self.priceLabel.setText(_translate("Dialog", "Price"))
        self.weightLabel.setText(_translate("Dialog", "Weight"))
        self.descriptionLabel.setText(_translate("Dialog", "Description"))
        self.availableQuantityLabel.setText(_translate("Dialog", "Available Quantity"))
        self.limitLabel.setText(_translate("Dialog", "Quantity Limit"))
        self.confirmButton.setText(_translate("Dialog", "Confirm"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        #self.imageUpload.setText(_translate("Dialog", "Upload Image \n\n\n Click to Upload \n or \n Drag and Drop"))
        
    def dragEnterEvent(self, event):
        """
        This event is triggered when a drag enters the widget.
        Check if the dragged data contains URLs (for image files).
        """
        if event.mimeData().hasUrls():
            event.acceptProposedAction()
            
    def dropEvent(self, event: QtGui.QDropEvent):
        """
        This event is triggered when a drop occurs.
        The dropped image is displayed using QLabel.
        """
        # Get the list of URLs from the MIME data
        urls = event.mimeData().urls()
        if urls:
            # Get the first image path and load it as a QPixmap
            file_path = urls[0].toLocalFile()
            pixmap = QtGui.QPixmap(file_path)
            if not pixmap.isNull():
                # Display the image in the QLabel
                self.imageUpload.setPixmap(pixmap.scaled(self.imageUpload.size(), aspectRatioMode=1))
                self.imageUpload.setText("")  # Clear the text when an image is dropped
            else:
                self.imageUpload.setText("Failed to load image!")
                
    def selectImage(self, event):
        """
        This method is triggered when the user clicks on the image label.
        It opens a file dialog to select an image.
        """
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Select Image", "", "Images (*.png *.xpm *.jpg *.jpeg)")
        if file_path:
            pixmap = QtGui.QPixmap(file_path)
            if not pixmap.isNull():
                # Display the image in the QLabel
                self.imageUpload.setPixmap(pixmap.scaled(self.imageUpload.size(), aspectRatioMode=1))
                self.imageUpload.setText("")  # Clear the text when an image is loaded
            else:
                self.imageUpload.setText("Failed to load image!")
                
import RetrieverEssentials_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
