# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomObjInCart.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
from PyQt5 import QtCore, QtGui, QtWidgets

import RetrieverEssentials_rc


class CustomObjInCart(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        
        self.setupUI()
        
    def setupUI(self):
        self.setObjectName("Form")
        self.resize(400, 87)
        
        self.objFrame1_1 = QtWidgets.QFrame(self)
        self.objFrame1_1.setGeometry(QtCore.QRect(9, 9, 222, 69))
        self.objFrame1_1.setFrameShape(QtWidgets.QFrame.Box)
        self.objFrame1_1.setLineWidth(1)
        self.objFrame1_1.setObjectName("objFrame1_1")
        
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.objFrame1_1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        
        self.label_13 = QtWidgets.QLabel(self.objFrame1_1)
        self.label_13.setMaximumSize(QtCore.QSize(75, 75))
        self.label_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        
        self.label_13.setPixmap(QtGui.QPixmap(u":/my_resources/Logos/Upload Image.png"))
        self.label_13.setScaledContents(True)
        self.horizontalLayout_13.addWidget(self.label_13)
        
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        
        self.label_14 = QtWidgets.QLabel(self.objFrame1_1)
        self.label_14.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        
        self.spinBox_6 = QtWidgets.QSpinBox(self.objFrame1_1)
        self.spinBox_6.setMaximumSize(QtCore.QSize(33, 16777215))
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_14.addWidget(self.spinBox_6)
        
        self.pushButton_7 = QtWidgets.QPushButton(self.objFrame1_1)
        self.pushButton_7.setMinimumSize(QtCore.QSize(46, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_14.addWidget(self.pushButton_7)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        
        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Custom Object in Cart"))
        self.label_13.setText(_translate("Form", "Object Image"))
        self.label_14.setText(_translate("Form", "Object Name - Weight"))
        self.pushButton_7.setText(_translate("Form", "Delete"))
        
    def set_image(self, image_path):
        pixmap = QtGui.QPixmap(image_path)
        self.label_13.setPixmap(pixmap.scaled(self.label_13.size(), QtCore.Qt.KeepAspectRatio))
        
    def set_object_name(self, name):
        self.label_14.setText(name)
        
    def set_weight(self,weight):
        self.label_14.setText(f"{self.label_14.text()} - {weight}")


class StudentInventoryView(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        
        self.setupUI()
        
    def setupUI(self):
        self.studentObjFrame = QtWidgets.QFrame(self)
        self.studentObjFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.studentObjFrame.setLineWidth(1)
        self.studentObjFrame.setMidLineWidth(1)
        self.studentObjFrame.setObjectName("studentObjFrame")
        
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.studentObjFrame)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        
        self.studentLabel = QtWidgets.QLabel(self.studentObjFrame)
        self.studentLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n""color: black;")
        self.studentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentLabel.setObjectName("studentLabel")
        self.studentLabel.setVisible(True)
        
        self.verticalLayout_1.addWidget(self.studentLabel)
        
        self.studentImage = QtWidgets.QGraphicsView(self.studentObjFrame)
        self.studentImage.setObjectName("studentImage")
        self.scene = QtWidgets.QGraphicsScene(self)
        self.studentImage.setScene(self.scene)
        
        self.pixmap = QtGui.QPixmap(":/my_resources/Logos/Canned Goods.jpg")  # Replace with your image path
        if not self.pixmap.isNull():
            self.imageItem = QtWidgets.QGraphicsPixmapItem(self.pixmap)  # Create an item for the image
            self.scene.addItem(self.imageItem)  # Add the image item to the scene
            
            resizedPixmap = self.pixmap.scaled(200, 150, QtCore.Qt.KeepAspectRatio)  # Resize to 200x150 pixels
            self.imageItem.setPixmap(resizedPixmap)
        else:
            print("Failed to load image.") 
            
        # Disable scrollbars on the QGraphicsView
        self.studentImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.studentImage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        self.resizeImage()
        self.verticalLayout_1.addWidget(self.studentImage)
        
        mainLayout = QtWidgets.QVBoxLayout(self)
        mainLayout.addWidget(self.studentObjFrame)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Student View of Inventory"))
        self.studentLabel.setText(_translate("Form", "Obj1 Title"))
        
    def resizeImage(self):
        view_width = self.studentImage.width()
        view_height = self.studentImage.height()
            
        resizedPixmap = self.pixmap.scaled(view_width, view_height, QtCore.Qt.KeepAspectRatio)
        self.imageItem.setPixmap(resizedPixmap)
            
    def resizeEvent(self, event):
        self.resizeImage()
        super().resizeEvent(event)
        
    def setObjName(self, name):
        self.studentLabel.setText(name)
        
    def setObjImage(self, file_path):
        self.pixmap = QtGui.QPixmap(file_path)  # Replace with your image path
        if not self.pixmap.isNull():
            self.imageItem = QtWidgets.QGraphicsPixmapItem(self.pixmap)  # Create an item for the image
            self.scene.addItem(self.imageItem)  # Add the image item to the scene
            
            resizedPixmap = self.pixmap.scaled(200, 150, QtCore.Qt.KeepAspectRatio)  # Resize to 200x150 pixels
            self.imageItem.setPixmap(resizedPixmap)
        else:
            print("Failed to load image.") 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = CustomObjInCart()
    
    #widget.set_image(":/my_resources/Logos/Retriever Essential.png")
    widget.set_object_name("Item Name")
    widget.set_weight("Weight")
    
    widget.show()
    sys.exit(app.exec_())

        
        
