# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewLoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(516, 513)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.StudentLoginTab = QtWidgets.QWidget()
        self.StudentLoginTab.setObjectName("StudentLoginTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.StudentLoginTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.StudentLoginTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.textEdit = QtWidgets.QTextEdit(self.StudentLoginTab)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 29))
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.StudentLoginTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.StudentLoginTab)
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 29))
        self.textEdit_2.setObjectName("textEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.StudentLoginTab)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.tabWidget.addTab(self.StudentLoginTab, "")
        self.StaffLoginTab = QtWidgets.QWidget()
        self.StaffLoginTab.setObjectName("StaffLoginTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.StaffLoginTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.StaffLoginTab)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textEdit_3 = QtWidgets.QTextEdit(self.StaffLoginTab)
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 29))
        self.textEdit_3.setObjectName("textEdit_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_3)
        self.label_4 = QtWidgets.QLabel(self.StaffLoginTab)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.textEdit_4 = QtWidgets.QTextEdit(self.StaffLoginTab)
        self.textEdit_4.setMaximumSize(QtCore.QSize(16777215, 29))
        self.textEdit_4.setObjectName("textEdit_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_4)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.StaffLoginTab)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.buttonBox_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.StaffLoginTab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setToolTip(_translate("Dialog", "<html><head/><body><p>Student Login</p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Student Login</p></body></html>"))
        self.label.setText(_translate("Dialog", "Username:"))
        self.label_2.setText(_translate("Dialog", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StudentLoginTab), _translate("Dialog", "Student Login"))
        self.label_3.setText(_translate("Dialog", "Username:"))
        self.label_4.setText(_translate("Dialog", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StaffLoginTab), _translate("Dialog", "Staff Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
