# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudentInventoryView_1.5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 262)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CategorySideBar = QtWidgets.QFrame(self.centralwidget)
        self.CategorySideBar.setFrameShape(QtWidgets.QFrame.Panel)
        self.CategorySideBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CategorySideBar.setLineWidth(1)
        self.CategorySideBar.setMidLineWidth(1)
        self.CategorySideBar.setObjectName("CategorySideBar")
        self.SideBarSearch = QtWidgets.QVBoxLayout(self.CategorySideBar)
        self.SideBarSearch.setContentsMargins(10, -1, 10, -1)
        self.SideBarSearch.setObjectName("SideBarSearch")
        self.retrieverEssentialLogo = QtWidgets.QLabel(self.CategorySideBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retrieverEssentialLogo.sizePolicy().hasHeightForWidth())
        self.retrieverEssentialLogo.setSizePolicy(sizePolicy)
        self.retrieverEssentialLogo.setMinimumSize(QtCore.QSize(0, 75))
        self.retrieverEssentialLogo.setMaximumSize(QtCore.QSize(75, 75))
        self.retrieverEssentialLogo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.retrieverEssentialLogo.setText("")
        self.retrieverEssentialLogo.setPixmap(QtGui.QPixmap(":/my_resources/Logos/Retriever Essential.png"))
        self.retrieverEssentialLogo.setScaledContents(True)
        self.retrieverEssentialLogo.setObjectName("retrieverEssentialLogo")
        self.SideBarSearch.addWidget(self.retrieverEssentialLogo)
        self.checkBoxLabel = QtWidgets.QLabel(self.CategorySideBar)
        self.checkBoxLabel.setEnabled(False)
        self.checkBoxLabel.setObjectName("checkBoxLabel")
        self.SideBarSearch.addWidget(self.checkBoxLabel)
        self.checkBox_1 = QtWidgets.QCheckBox(self.CategorySideBar)
        self.checkBox_1.setObjectName("checkBox_1")
        self.SideBarSearch.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.CategorySideBar)
        self.checkBox_2.setObjectName("checkBox_2")
        self.SideBarSearch.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.CategorySideBar)
        self.checkBox_3.setObjectName("checkBox_3")
        self.SideBarSearch.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.CategorySideBar)
        self.checkBox_4.setObjectName("checkBox_4")
        self.SideBarSearch.addWidget(self.checkBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SideBarSearch.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SideBarSearch.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 308, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SideBarSearch.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.CategorySideBar)
        self.NonSideBar = QtWidgets.QVBoxLayout()
        self.NonSideBar.setObjectName("NonSideBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SearchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchBar.setObjectName("SearchBar")
        self.horizontalLayout_3.addWidget(self.SearchBar)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SortByLabel = QtWidgets.QLabel(self.centralwidget)
        self.SortByLabel.setObjectName("SortByLabel")
        self.horizontalLayout_2.addWidget(self.SortByLabel)
        self.SortByComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SortByComboBox.sizePolicy().hasHeightForWidth())
        self.SortByComboBox.setSizePolicy(sizePolicy)
        self.SortByComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.SortByComboBox.setObjectName("SortByComboBox")
        self.SortByComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.SortByComboBox)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.GoToCartButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoToCartButton.sizePolicy().hasHeightForWidth())
        self.GoToCartButton.setSizePolicy(sizePolicy)
        self.GoToCartButton.setMinimumSize(QtCore.QSize(75, 23))
        self.GoToCartButton.setMaximumSize(QtCore.QSize(100, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/my_resources/Logos/CheckoutCart1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.GoToCartButton.setIcon(icon)
        self.GoToCartButton.setObjectName("GoToCartButton")
        self.horizontalLayout.addWidget(self.GoToCartButton)
        self.NonSideBar.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 306, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        """self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)"""
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.NonSideBar.addWidget(self.scrollArea)
        self.horizontalLayout_4.addLayout(self.NonSideBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.uploadInventoryView()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxLabel.setText(_translate("MainWindow", "Catagories"))
        self.checkBox_1.setText(_translate("MainWindow", "Cat1"))
        self.checkBox_2.setText(_translate("MainWindow", "Cat2"))
        self.checkBox_3.setText(_translate("MainWindow", "Cat3"))
        self.checkBox_4.setText(_translate("MainWindow", "Cat4"))
        self.SearchBar.setText(_translate("MainWindow", "Search Bar"))
        self.SortByLabel.setText(_translate("MainWindow", "Sort By:"))
        self.SortByComboBox.setItemText(0, _translate("MainWindow", "Name"))
        self.GoToCartButton.setText(_translate("MainWindow", "Go To Cart"))

    def uploadInventoryView(self):
        columns = 4
        item_count = 50 # temp variable for testing, will be changed to iterate through database
        
        grid_width = self.gridLayout_3.sizeHint().width()
        grid_height = self.gridLayout_3.sizeHint().height()
            
        item_width = grid_width // columns
        item_height = grid_height // (item_count // columns)
            
        for i in range(item_count):
            col = i % columns
            row = i // columns
            
            self.addInventoryItem = StudentInventoryView()
            self.addInventoryItem.setObjName(str(i+1)) # replace this with the object's name
            self.addInventoryItem.setObjImage(":/my_resources/Logos/Canned Goods.jpg") # replace this with the image file_path
            self.addInventoryItem.resizeImage()
            self.addInventoryItem.resize(item_width, item_height)
            self.gridLayout_3.addWidget(self.addInventoryItem, row, col, 1, 1)

import RetrieverEssentials_rc
from CustomObj import StudentInventoryView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
