# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomObjInCart.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
from PyQt5 import QtCore, QtGui, QtWidgets

import UserInterface.RetrieverEssentials_rc


class CustomObjInCart(QtWidgets.QWidget):
    """For Removing Items from the checkout screen"""
    deletePressed = QtCore.pyqtSignal(object)
    quantityChange = QtCore.pyqtSignal(object)
    
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUI()
        
    def setupUI(self):
        self.objFrame1_1 = QtWidgets.QFrame(self)
        self.objFrame1_1.setGeometry(QtCore.QRect(9, 9, 222, 69))
        self.objFrame1_1.setFrameShape(QtWidgets.QFrame.Box)
        self.objFrame1_1.setLineWidth(1)
        self.objFrame1_1.setObjectName("objFrame1_1")
        
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.objFrame1_1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        
        self.label_13 = QtWidgets.QLabel(self.objFrame1_1)
        self.label_13.setMaximumSize(QtCore.QSize(75, 75))
        self.label_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        
        self.label_13.setPixmap(QtGui.QPixmap(u":/my_resources/Logos/Upload Image.png"))
        self.label_13.setScaledContents(True)
        self.horizontalLayout_13.addWidget(self.label_13)
        
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        
        self.label_14 = QtWidgets.QLabel(self.objFrame1_1)
        self.label_14.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        
        self.spinBox_6 = QtWidgets.QSpinBox(self.objFrame1_1)
        self.spinBox_6.setMaximumSize(QtCore.QSize(33, 16777215))
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_6.setMinimum(1)
        
        self.horizontalLayout_14.addWidget(self.spinBox_6)
        
        self.deleteButton = QtWidgets.QPushButton(self.objFrame1_1)
        self.deleteButton.setMinimumSize(QtCore.QSize(46, 0))
        self.deleteButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_14.addWidget(self.deleteButton)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        
        """For Removing Items from the checkout screen"""
        self.deleteButton.clicked.connect(self.emiteDeleteSignal)
        self.spinBox_6.valueChanged.connect(self.spinBoxValueChange)
        
        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Custom Object in Cart"))
        self.label_13.setText(_translate("Form", "Object Image"))
        self.label_14.setText(_translate("Form", "Object Name - Weight"))
        self.deleteButton.setText(_translate("Form", "Delete"))
        
    def set_image(self, image_path):
        pixmap = QtGui.QPixmap(image_path)
        self.label_13.setPixmap(pixmap.scaled(self.label_13.size(), QtCore.Qt.KeepAspectRatio))
        
    def set_object_name(self, name):
        self.label_14.setText(name)
        
    def set_weight(self,weight):
        self.label_14.setText(f"{self.label_14.text()} - {weight}")
        
    def set_quantity_in_cart(self, quantity):
        self.spinBox_6.setValue(quantity)
    
    """
    This sets the maximum number of items that can be grabbed
    """
    def set_max_quantity(self, max):
        self.spinBox_6.setMaximum(max)
        
    """For Removing Items from the checkout screen"""
    def emiteDeleteSignal(self):
        self.deletePressed.emit(self)
        
    """For changing the value of the spinBox"""
    def spinBoxValueChange(self):
        self.quantityChange.emit(self)

class StudentInventoryView(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        
        self.setupUI()
        
    def setupUI(self):
        self.studentObjFrame = QtWidgets.QFrame(self)
        self.studentObjFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.studentObjFrame.setLineWidth(1)
        self.studentObjFrame.setMidLineWidth(1)
        self.studentObjFrame.setObjectName("studentObjFrame")
        
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.studentObjFrame)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        
        self.studentLabel = QtWidgets.QLabel(self.studentObjFrame)
        self.studentLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n""color: black;")
        self.studentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentLabel.setObjectName("studentLabel")
        self.studentLabel.setVisible(True)
        
        self.verticalLayout_1.addWidget(self.studentLabel)
        
        self.studentImage = QtWidgets.QGraphicsView(self.studentObjFrame)
        self.studentImage.setObjectName("studentImage")
        self.scene = QtWidgets.QGraphicsScene(self)
        self.studentImage.setScene(self.scene)
        
        self.pixmap = QtGui.QPixmap(":/my_resources/Logos/Canned Goods.jpg")  # Replace with your image path
        if not self.pixmap.isNull():
            self.imageItem = QtWidgets.QGraphicsPixmapItem(self.pixmap)  # Create an item for the image
            self.scene.addItem(self.imageItem)  # Add the image item to the scene
            
            resizedPixmap = self.pixmap.scaled(200, 150, QtCore.Qt.KeepAspectRatio)  # Resize to 200x150 pixels
            self.imageItem.setPixmap(resizedPixmap)
        else:
            print("Failed to load image.") 
            
        # Disable scrollbars on the QGraphicsView
        self.studentImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.studentImage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        self.resizeImage()
        self.verticalLayout_1.addWidget(self.studentImage)
        
        mainLayout = QtWidgets.QVBoxLayout(self)
        mainLayout.addWidget(self.studentObjFrame)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Student View of Inventory"))
        self.studentLabel.setText(_translate("Form", "Obj1 Title"))
        
    def resizeImage(self):
        view_width = self.studentImage.width()
        view_height = self.studentImage.height()
            
        resizedPixmap = self.pixmap.scaled(view_width, view_height, QtCore.Qt.KeepAspectRatio)
        self.imageItem.setPixmap(resizedPixmap)
            
    def resizeEvent(self, event):
        self.resizeImage()
        super().resizeEvent(event)
        
    def setObjName(self, name):
        self.studentLabel.setText(name)
        
    def setObjImage(self, file_path):
        self.pixmap = QtGui.QPixmap(file_path)  # Replace with your image path
        if not self.pixmap.isNull():
            self.imageItem = QtWidgets.QGraphicsPixmapItem(self.pixmap)  # Create an item for the image
            self.scene.addItem(self.imageItem)  # Add the image item to the scene
            
            resizedPixmap = self.pixmap.scaled(200, 150, QtCore.Qt.KeepAspectRatio)  # Resize to 200x150 pixels
            self.imageItem.setPixmap(resizedPixmap)
        else:
            print("Failed to load image.") 
        
        
    

class StaffInventoryView(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        
        self.setupUI()
        
    def setupUI(self):
        self.staffObjFrame = QtWidgets.QFrame(self)
        self.staffObjFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.staffObjFrame.setLineWidth(1)
        self.staffObjFrame.setMidLineWidth(1)
        self.staffObjFrame.setObjectName("staffObjFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.staffObjFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.staffObjLabel = QtWidgets.QLabel(self.staffObjFrame)
        self.staffObjLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n""color: black;")
        self.staffObjLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.staffObjLabel.setObjectName("staffObjLabel")
        self.verticalLayout_2.addWidget(self.staffObjLabel, 0, QtCore.Qt.AlignHCenter)
        self.staffObjImage = QtWidgets.QGraphicsView(self.staffObjFrame)
        self.staffObjImage.setObjectName("staffObjImage")
        self.scene = QtWidgets.QGraphicsScene(self)
        self.staffObjImage.setScene(self.scene)
        self.verticalLayout_2.addWidget(self.staffObjImage)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editItemButton = QtWidgets.QPushButton(self.staffObjFrame)
        self.editItemButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: white;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/my_resources/Logos/Edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editItemButton.setIcon(icon)
        self.editItemButton.setObjectName("editItemButton")
        self.horizontalLayout.addWidget(self.editItemButton)
        self.removeItemButton = QtWidgets.QPushButton(self.staffObjFrame)
        self.removeItemButton.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/my_resources/Logos/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeItemButton.setIcon(icon1)
        self.removeItemButton.setObjectName("removeItemButton")
        self.horizontalLayout.addWidget(self.removeItemButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(self)
        
        self.pixmap = QtGui.QPixmap(":/my_resources/Logos/Canned Goods.jpg")  # Replace with your image path
        if not self.pixmap.isNull():
            self.imageItem = QtWidgets.QGraphicsPixmapItem(self.pixmap)  # Create an item for the image
            self.scene.addItem(self.imageItem)  # Add the image item to the scene
            
            resizedPixmap = self.pixmap.scaled(200, 150, QtCore.Qt.KeepAspectRatio)  # Resize to 200x150 pixels
            self.imageItem.setPixmap(resizedPixmap)
        else:
            print("Failed to load image.") 
            
        # Disable scrollbars on the QGraphicsView
        self.staffObjImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.staffObjImage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        self.resizeImage()
        #self.verticalLayout_2.addWidget(self.staffObjImage)
        
        mainLayout = QtWidgets.QVBoxLayout(self)
        mainLayout.addWidget(self.staffObjFrame)
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.staffObjLabel.setText(_translate("Form", "Obj1 Title"))
        self.editItemButton.setText(_translate("Form", "Edit"))
        self.removeItemButton.setText(_translate("Form", "Remove"))
        
    def resizeImage(self):
        view_width = self.staffObjImage.width()
        view_height = self.staffObjImage.height()
            
        resizedPixmap = self.pixmap.scaled(view_width, view_height, QtCore.Qt.KeepAspectRatio)
        self.imageItem.setPixmap(resizedPixmap)
            
    def resizeEvent(self, event):
        self.resizeImage()
        super().resizeEvent(event)
        
    def setObjName(self, name):
        self.staffObjLabel.setText(name)
        
    def setObjImage(self, file_path):
        self.pixmap = QtGui.QPixmap(file_path)  # Replace with your image path
        if not self.pixmap.isNull():
            self.imageItem = QtWidgets.QGraphicsPixmapItem(self.pixmap)  # Create an item for the image
            self.scene.addItem(self.imageItem)  # Add the image item to the scene
            
            resizedPixmap = self.pixmap.scaled(200, 150, QtCore.Qt.KeepAspectRatio)  # Resize to 200x150 pixels
            self.imageItem.setPixmap(resizedPixmap)
        else:
            print("Failed to load image.") 
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = StaffInventoryView()
    #widget.setObjName("Test 2")
    
    #widget.set_image(":/my_resources/Logos/Retriever Essential.png")
    #widget.set_object_name("Item Name")
    #widget.set_weight("Weight")
    
    widget.show()
    sys.exit(app.exec_())

        
        
